<?php
$dbconn=mysql_connect("localhost","sothink","K2v3P494");
mysql_select_db("cart",$dbconn);
$users=users;
$gouwuquan=gouwuquan;
$gouwuquaninfo=gouwuquaninfo;
$discountd=discountd;
$discountc=discountc;
$discountq=discountq;
$ordersp=ordersp;
$orders=orders;
$paymodeinfo=paymodeinfo;
$tbBasket=tbBasket;
$tbProduct=tbProduct;
$paypalorder=paypalorder;
$paypalordersp=paypalordersp;
$regcode=regcode;
?>