str="<h3>产品盒</h3>";
str=str+"	<div id=\"showbox\"><img src=\"/images/system/box/box-Quicker.gif\" width=\"90\" height=\"158\" /><br /><img src=\"/images/system/wVista-Works.png\" /> </div>";
str=str+"<h3>产品信息 </h3>";
str=str+"<div id=\"soft-info\">";
str=str+"	<dl>";
str=str+"		<dt id=\"first\">文件大小：</dt>";
str=str+"			<dd>5.02MB </dd>";
str=str+"		<dt>最新版本：</dt>";
str=str+"			<dd>1.5 </dd>";
str=str+"		<dt>版本号：</dt>";
str=str+"			<dd>41230 </dd>";
str=str+"		<dt>完全卸载： </dt>";
str=str+"			<dd>支持</dd>";
str=str+"		<dt>英文版： </dt>";
str=str+"			<dd><a href=\"http://www.sothink.com/product/swfquicker/index.htm\" target=\"_blank\">查看最新版信息</a></dd>";
str=str+"	</dl>";
str=str+"</div>";
str=str+"<h3>相关产品</h3>";
str=str+"<div id=\"soft-info\">";
str=str+"	<dl>";
str=str+"		<dt id=\"first\">硕思闪客精灵</dt>";
str=str+"			<dd><a href=\"/product/flashdecompiler/index.htm\" target=\"_blank\">产品简介</a></dd>";
str=str+"			<dd><a href=\"/product/flashdecompiler/download.htm\" target=\"_blank\">免费下载</a></dd>";
str=str+"			<dd><a href=\"/product/flashdecompiler/whatsnew.htm\" target=\"_blank\">版本更新历史</a></dd>";
str=str+"	</dl>";
str=str+"</div>";
str=str+"<div id=\"soft-info\">";
str=str+"	<dl>";
str=str+"		<dt id=\"first\">硕思闪客巫师</dt>";
str=str+"			<dd><a href=\"/product/swfeasy/index.htm\" target=\"_blank\">产品简介</a></dd>";
str=str+"			<dd><a href=\"/product/swfeasy/download.htm\" target=\"_blank\">免费下载</a></dd>";
str=str+"			<dd><a href=\"/product/swfeasy/whatsnew.htm\" target=\"_blank\">版本更新历史</a></dd>";
str=str+"	</dl>";
str=str+"</div>";
document.write(str);