<?php
$_g_lang['letter']['no_exper_help'] = '沒有任何請求幫助歷練的探報！';
$_g_lang['letter']['all_help_cpl'] = '已説明所有需要歷練的朋友！';
$_g_lang['letter']['invite_false'] = '邀請已失效！';
$_g_lang['letter']['ill_request'] = '非法請求！';
$_g_lang['letter']['meet_cond_invite_false'] = '該好友歷練條件已滿足，邀請已失效！';
$_g_lang['letter']['no_find_letter'] = '信件不存在';
$_g_lang['letter']['no_friend_no_gift'] = '用戶已解除好友關係，不能送禮';
$_g_lang['letter']['today_gift_no_again'] = '你今天已經給過他禮物了，不能再給了';
$_g_lang['letter']['error_pinfo'] = '帳號數據出錯';
$_g_lang['letter']['gift_no_find'] = '該禮物已被打劫';
$_g_lang['letter']['pack_full_to_give'] = '包裹已滿，無法領取';
$_g_lang['letter']['get_from_letter_info'] = '獲得了%s個%s';
$_g_lang['letter']['f_get_coins'] = "獲得了%s個銅錢";
$_g_lang['letter']['f_get_silver'] = "獲得了%s個銀票";
$_g_lang['letter']['f_get_ingot'] = "獲得了%s個元寶";
$_g_lang['letter']['f_get_grain'] = "獲得了%s個軍糧";
$_g_lang['letter']['no_fri_request'] = '沒有任何好友請求';
$_g_lang['letter']['friend_limit'] = '您的好友數已達上限';
$_g_lang['letter']['no_find_sy_letter'] = '沒有任何索要的信件';
$_g_lang['letter']['error_level'] = '非法請求的等級';
$_g_lang['letter']['no_find_gift'] = '沒有任何可領取的禮物';
$_g_lang['letter']['pack_full_please_to'] = '您背包已滿，請先清理或擴容';
$_g_lang['letter']['get_all_gift'] = '已領取所有禮物';
$_g_lang['letter']['no_find_gift_letter'] = '沒有任何被贈送禮物的探報';
$_g_lang['letter']['sys_occupy_public'] = "【群雄逐鹿】 “%s活動”在“%s”的佔領者是“%s”，獲得額外收益";
$_g_lang['letter']['sys_big_award_public'] = "【群雄逐鹿】恭喜！“%s”在“%s”中獲得令人垂涎的“%s級逐鹿大獎”";
$_g_lang['letter']['sys_open_award_public'] = "【群雄逐鹿】“%s”打開“%s級逐鹿大獎”";
$_g_lang['letter']['sys_git_award_public'] = "【群雄逐鹿】本次“%s級逐鹿大獎”開出“%s”";
$_g_lang['letter']['sys_admin_public'] = "%s";
$_g_lang['letter']['sys_top_scorer_public'] = "【群雄逐鹿】“%s”在“%s活動”中佔領時間最長，榮獲得分王大獎";

$_g_lang['letter']['pack_full_please_to'] = $_g_lang['letter']['pack_full_to_give'] = "不能領取！\n背包已滿，請先整理或擴容！";
$_g_lang['letter']['f_get_sw'] = "獲得了%s點聲望";
